/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as jayDerivSol from "./JayDeriv.sol";
export type { jayDerivSol };
import type * as jayErc20Sol from "./JayERC20.sol";
export type { jayErc20Sol };
import type * as jayMartSol from "./JayMart.sol";
export type { jayMartSol };
import type * as test from "./test";
export type { test };
export type { JayDerivFeeSplitter } from "./JayDerivFeeSplitter";
export type { JayDerivLiquidityStaking } from "./JayDerivLiquidityStaking";
export type { JayFeeSplitter } from "./JayFeeSplitter";
export type { JayLiquidityStaking } from "./JayLiquidityStaking";
