/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as jayErc20Sol from "./JayERC20.sol";
export type { jayErc20Sol };
import type * as jayMartSol from "./JayMart.sol";
export type { jayMartSol };
import type * as test from "./test";
export type { test };
export type { JAYusingContractBal } from "./JAYusingContractBal";
export type { JayFeeSplitter } from "./JayFeeSplitter";
export type { JayLiquidityStaking } from "./JayLiquidityStaking";
