/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as jayErc20Sol from "./JayERC20.sol";
export type { jayErc20Sol };
import type * as jayProtocolSol from "./JayProtocol.sol";
export type { jayProtocolSol };
import type * as test from "./test";
export type { test };
export type { JayFeeSplitter } from "./JayFeeSplitter";
export type { JayLiquidityStaking } from "./JayLiquidityStaking";
