/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as erc1155Sol from "./erc1155.sol";
export type { erc1155Sol };
import type * as nftSol from "./nft.sol";
export type { nftSol };
import type * as nftBadSol from "./nftBad.sol";
export type { nftBadSol };
