/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { JayDerivFeeSplitter } from "./JayDerivFeeSplitter";
export type { JayFeeSplitter } from "./JayFeeSplitter";
