/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as erc1155Sol from "./erc1155.sol";
export * as nftSol from "./nft.sol";
export * as nftBadSol from "./nftBad.sol";
